{% set name = "python_version" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_version-{{ version }}.tar.gz
  sha256: 5c16de57c7f2d614621cf468e8f5a20bb6b3cec665c9c7f5e9f9f000bf04fe67

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - python_version
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/halfak/python_version
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Provides a simple utility for checking the python version.'
  description: |
    This package provides a basic python version checking utility. It
    will check for a range of python versions and either report an error
    or exit depending on the parameters provided.
  doc_url: https://gitlab.com/halfak/python_version
  dev_url: https://gitlab.com/halfak/python_version

extra:
  recipe-maintainers:
    - jan-janssen
